### ISSUE TITLE
Bibliographic API data transform script

### ISSUE THREAD

**Issue by davidamichelson** [srophe/util#1]
@wsalesky Will add details shortly. The purpose of this script is to take results from the Worldcat API and transform them into a format for easy import into Zotero that maintains the full citation including the OCLC number and other identifiers (ISBN, ISSN, DOI, etc).

**Comment by wlpotter** [comment]
The API response from Worldcat is in the form of MARCXML records, and I have tried using Zotero's import function. This has worked for the most part, but it won't grab the OCLC number. I've attached a sample below, as a .txt since Github doesn't allow uploading XML in comments (I also did some post-processing on the API return to get it into a form that Zotero's import would read). The OCLC number is in the `marc:controlfield[@tag=001]` text node.

We would want the OCLC number to be entered as a new-line separated key: value pair in the 'Extra' field in Zotero; e.g. "OCLC: 973317620". 


[testZoteroImportMarcXML.txt](https://github.com/srophe/util/files/4087321/testZoteroImportMarcXML.txt)

**Comment by wlpotter** [comment]
I have a related question about the output of my API calls. I am using XQuery to extract the marc:record element and then wrapping it in a marc:collection element.

I am running the script that makes the API calls on a list of bibliographic citations, and I could return the responses either as a single file containing a sequence of marc:record elements nested in a marc:collection element:

```
<collection xmlns="http://www.loc.gov/MARC21/slim">
    <record>
        <!-- data -->
    </record>
    <record>
        <!-- data -->
    </record>
    <record>
        <!-- data -->
    </record>
<!-- etc. -->
</collection>
```

Or I could return a file for each response, in which case I would have multiple files but each would consist only of a marc:collection element with a single marc:record child. 

Is one of these more advantageous than the other? Or is it somewhat a matter of preference?

**Comment by wlpotter** [comment]
Putting a hold on this for now.

**Comment by wlpotter** [comment]
This is working, see the script here: https://github.com/wlpotter/miscellaneous-util-scripts/blob/master/Caesarea-Biblio-Api/worldCatApiLookup.xq

Note for the future: importing into Zotero can only be done one file at a time, so it is better to create a single MARCXML file, with a single collection encasing as many children as needed. I had already written the above lookup script and run it on a few test records, so I have simply run the returns through a script that collects the records into a single marc:collection, https://github.com/wlpotter/miscellaneous-util-scripts/blob/master/Caesarea-Biblio-Api/compileMarcXMLCollection.xq
